language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.22"
  - "5.24"
  - "blead"
sudo: false
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
matrix:
  allow_failures:
    - perl: blead
